language: node_js
node_js:
    - "4"
    - "6"
sudo: required
services: mysql
before_install:
  - mysql -u root -e "CREATE DATABASE parkinglot";
after_script:
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN > /dev/null
