language: node_js
node_js:
    - "4"
    - "6"
sudo: required
addons:
    apt:
        packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
before_install:
  - mysql -u root -e "CREATE DATABASE parkinglot";
after_script:
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN > /dev/null
